### PR TITLE
New screens

### PR DESCRIPTION
**Pull request by adamhutchings**

### CODE REVIEW

**Review by S-Mackenzie1678 — APPROVED** [review]
The q and the enter cause color changing. Yay!

**Comment by EmilyTLin** [comment]
Would it better to be the states ("menu," "escaped," "main") to be enums?

**Review by EmilyTLin — APPROVED** [review]
Seems legit (if we don't want to do the states as enums)

**Comment by adamhutchings** [comment]
I'm a little uncomfy with enums. I'll fix it later or assign someone to it.

**Pull request merged**
