### PR TITLE
Add ocean theme

### LINKED ISSUE #17: Add ocean theme

### PR DESCRIPTION
**Pull request by LudiWang85454**
Closes #17

### CODE REVIEW

**Review by S-Mackenzie1678 — APPROVED** [review]
[OUTDATED]

F it took a while sorry

**Review by S-Mackenzie1678 — CHANGES_REQUESTED** [review]
We've changed formats for music. We're using .ogg files now. MuseScore can export them if you're on the most recent version.

**Comment by LudiWang85454** [comment]
Oh yeah my bad I'll change it

**Review by S-Mackenzie1678 — APPROVED** [review]
Oh yes that danq file format

**Pull request merged**
